version: "3"

volumes:
  data: {}

services:
  activemq:
    image: webcenter/activemq:5.14.3
    environment:
      - ACTIVEMQ_MIN_MEMORY=128
      - ACTIVEMQ_MAX_MEMORY=1024
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
      - ACTIVEMQ_OWNER_LOGIN=admin
      - ACTIVEMQ_OWNER_PASSWORD=password
    volumes:
      - ./assets/activemq/activemq.xml:/opt/activemq/conf/activemq.xml:ro

  opencast:
    image: quay.io/opencast/allinone:8.1
    environment:
      - ORG_OPENCASTPROJECT_SERVER_URL=http://localhost:8080
      - ORG_OPENCASTPROJECT_DOWNLOAD_URL=http://localhost:8080/static
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=admin
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=opencast
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=opencast_system_account
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=CHANGE_ME
      - ACTIVEMQ_BROKER_URL=failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      - ACTIVEMQ_BROKER_USERNAME=admin
      - ACTIVEMQ_BROKER_PASSWORD=password
    ports:
      - "8080:8080"
    volumes:
      - data:/data
      - ./assets/opencast/workflows:/opencast/etc/workflows

      - ./assets/opencast/listproviders:/etc/opencast/listproviders
      - ./assets/opencast/custom.properties:/etc/opencast/custom.properties
      - ./assets/opencast/org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg:/etc/opencast/org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg
      - ./assets/opencast/org.opencastproject.ui.metadata.CatalogUIAdapterFactory-turing.cfg:/etc/opencast/org.opencastproject.ui.metadata.CatalogUIAdapterFactory-turing.cfg
